# This is a basic workflow to help you get started with Actions

name: Deploy via git-ftp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
